### ISSUE TITLE
Doesn't work with #ifdefs marks the scope as global after 

### ISSUE THREAD

**Issue by alfaiyma** [mrkschan/ctags-status#35]

**Comment by mrkschan** [comment]
Hi @alfaiyma, would you mind providing a simple code sample that demonstrate the issue?

**Comment by alfaiyma** [comment]
Sorry for the late response but any code within an ifdef block in c reverts
to [global]
I.e
Void fun() {
int i;
#ifdef 1
i=1
#endif
}

**Comment by pbraga** [comment]
same problem here, should ignore pre-compile directives (#)

**Comment by mrkschan** [comment]
@pbraga @alfaiyma which ctags-status version are you using? And, what is the file extension of the file? .c or other file extension?

I cannot reproduce on ctags-status v1.3.5

```
// c.c


Void fun() {
  int i;
  #ifdef 1
  i=1
  #endif
}
```

**Comment by pbraga** [comment]
I am using ctags-status v1.3.5 as well, and the files are .c and .h files.
It could be due to indentation as the pre compile directives do not have any in the project i am working on. So mostly like your example but with #ifdef and #endif at the same level the function.
I have not been able to properly test this.

**Comment by mrkschan** [comment]
Confirmed with the one below.

```
int f3() {
    int i;
#ifdef 1
    i=1
#endif
    return 0;
}
```

**Comment by mrkschan** [comment]
Hey, try v1.3.6.

**Comment by pbraga** [comment]
Hi, I have just tested with new version and it does work :)
You can close this issue ;)
Thank you
